ARG baseimage="devopsubuntu16.04:latest"
FROM ${baseimage}

COPY scripts /scripts

RUN /scripts/installers/docker-moby.sh && \
    /scripts/installers/docker-compose.sh && \
    /scripts/installers/kubernetes-tools.sh

